version: "3.9"
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sportsline
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
